### ISSUE TITLE
Allow use of non-(string literals) in `query!()`

### ISSUE THREAD

**Issue by PauMAVA** [roy-ganz/toql#6]
Hello! First of all, thanks for developing this amazing ORM!

I was wondering if we could add support for using non-string literals for the `query` parameter inside the query macro `query!` so that toql query strings can be constructed both at compile time (statically) and at runtime. 

For example, let's say I have a user provided toql query. Then I could do the following:
```rust
query!(User, query, user_name, password);
```
Currently, this throws a compile error:
```
error: expected literal
```

I don't think this would be very difficult to implement, just changing the `query_macro` and `query_parse` crates to accept both `LitStr` and `Ident` would do the trick. Then if the `Ident` value can not be converted to a string, we would throw a compile error.  This is because [`pest`](https://docs.rs/pest/latest/pest/index.html)::[`Parser`](https://docs.rs/pest/latest/pest/trait.Parser.html)::[`parse`](https://docs.rs/pest/latest/pest/trait.Parser.html#tymethod.parse) takes a `&str` variable.

I can try to implement it and open a PR if you think this would be a good addition. 😄

**Comment by roy-ganz** [comment]
Hi, thanks for trying Toql.
The purpose of the `query!` macro is to give _compile time_ guarantees, that your query syntax and all field names are correct. The macro does this by parsing the string literal at _compile time_ and turns it into Rust source code for the Rust compiler. (Similar to the well known `format!` macro).
This is only possible when the query is a string literal. It's not possible with variables, because their value is not known at _compile time_.

However you have several options to trade safety versus flexibility. The most flexible is the `QueryParser`, in between are the `Query<T>`  builder methods and for most safety is `query!`.  It's possible to mix the different methods, see the [manual](https://roy-ganz.github.io/toql_guide/3-api/3-query-type.html).
 
If you give me more context about what you want to do, I can provide you a more detailed answer.

**Comment by PauMAVA** [comment]
Yes. I figured that out later. Let me explain my use case. 

I am developing an API with rocket.rs that has only one endpoint (with dynamic paths) for model searching, for example: `/api/v1/search/<model_name>?<filters>`. In the endpoint, the `model_name` uses the `&str` request guard and the `filters` is a `HashMap<&str, &str>`.

The idea was to have a single endpoint function from which I could serve any response (I have done this using `Box<dyn erased_serde::Serialize>`) and filter any model. The `filters` hash map is a map containing the query parameters which are used to filter the model. Example:
```
/api/v1/search/person?max-id=1&like-name=Jo
```
So, to implement this, it would have been great to be able to generate Toql instructions dynamically at runtime.

I finally ended up using the `Query<T>` builder method and created a macro that implements a search function for a certain model by parsing the filters and calling the appropriate functions on `Query<T>`. 

Maybe what I missed was the manual explaining more clearly the following syntax (maybe it's in the manual but I haven't seen it):
```rust
let query = Query<Person>::new().id().lt(1).name().lk("Jo");
```

Thanks for your response and for making this ORM!

It's a really complete ORM that supports everything and API needs (pagination, related models filtering...) and it's also easy to use.

**Comment by roy-ganz** [comment]
I see. This should work:
``` rust  
    use toql::prelude::{Field, Query};
    use std::collections::HashMap;

    let mut filter : HashMap<String, String> = HashMap::new();
    filter.insert("name".to_string(), "peter".to_string());

    let mut q1: Query<Person>= Query::new();
    for(k,v) in filter {
        let field = Field::from(k);
        query = query.and(field.eq(v));
    }
```
Notice you can mix the different builder methods. Let's say you want to load some fields with your filter:
```rust 
let q2 = query!(Person, "age, {}", q1);
```
Yes, Toql is pretty complete (after 3 years of tinkering). I use it myself for a web service with about 50K lines of code (mostly db related) and about 70 database tables that are linked in all kind of ways. It's a pretty smooth experience for me. Esp. compile time guarantees - `query!` and others - really pay off once the project grows.

I close the issue for now. Have a nice day.
